config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  
  resources :users do
  end
  
  resources :forums
  resources :topics
  resources :posts
  
  resources :sessions
  get "login" => "sessions#new", as: :login
  get "signup" => "users#new", as: :signup
  get "home" => "users#index", as: :home
  
  get "lawyers" => "users#lawyers", as: :lawyers
  
  resources :password_resets, only: %w(new create edit update)
  
  get '/404', to: 'errors#not_found'
  get '/422' => 'errors#server_error'
  get '/500' => 'errors#server_error'

end

app/models/forum.rb
class Forum < ActiveRecord::Base
  has_many :topics, :dependent => :destroy
  
  def most_recent_post
    topic = Topic.where(['forum_id = ?', self.id]).map(&:posts).flatten.map(&:created_at).max
  end
  
  def most_recent_poster
    topic = Topic.where(['forum_id = ?', self.id]).map(&:posts).flatten.last.user
  end
  
  def sorted_topics
    topics.sort {|a,b| b.last_post_at <=> a.last_post_at}
  end
  
  def sorted_topics_array
    array = []
    sorted_topics.each do |topic|
      array << topic.id
    end
    array
  end
  
  def next_topic(topic_id)
    index = sorted_topics_array.index(topic_id)
    if sorted_topics_array.size > index && sorted_topics_array[index+1].present?
      topic_id = sorted_topics_array[index+1]
    else
      topic_id = sorted_topics_array.first
    end
    Topic.find(topic_id)
  end
  
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :authenticate_user!
  #TODO authenticate user
  
  def index
    @forums = Forum.all
    @user = current_user
  end
  
  def new
    @user = current_user
    @forum = Forum.new
  end
  
  def edit
    
  end
  
  def create
    @forum = Forum.new(forum_params)
    if @forum.save
      redirect_to @forum 
    else
      render :new
    end
  end
  
  def show
    @user = current_user
    @forum = Forum.find(params[:id])
    @topics = @forum.topics.sort {|a,b| b.last_post_at <=> a.last_post_at}
    @posts = Post.all.each.sort {|a,b| b.created_at <=> a.created_at}
  end
  
  protected
  
  def forum_params
    params.require(:forum).permit(:name, :description)
  end
  
end

app/views/forums/new.html.erb
<!DOCTYPE html>
<!-- 
TEMPLATE NAME : Adminre backend
VERSION : 1.2.0
AUTHOR : JohnPozy
AUTHOR URL : http://themeforest.net/user/JohnPozy
EMAIL : pampersdry@gmail.com
LAST UPDATE: 23/06/2014

** A license must be purchased in order to legally use this template for your project **
** PLEASE SUPPORT ME. YOUR SUPPORT ENSURE THE CONTINUITY OF THIS PROJECT **
-->
<html class="backend">
  <%= render 'shared/backend_head' %>
  <%#= render 'shared/header' %>

  <!-- START Body -->
  <body>
  	

  	 <%= render 'shared/header_member' %>
  	 <!-- START Template Main -->
    <section id="main" role="main">
    	<%#= render 'shared/navigation_member_secondary' %>

      

		  <!-- START row -->
      <div class="row">
        <div class="col-md-6 col-md-offset-3">

        	<br/>
        	<br/>
        	<br/>

    	    <!-- panel heading -->
		      <div class="panel-heading">
		        <h3 class="semibold text-default text-center">New Forum Topic or Question</h3>
		        <!-- panel toolbar -->
		        <div class="panel-toolbar">
		         
		        </div>
		      </div>
		      <!--/ panel heading -->


          <!-- START panel -->
          <div class="panel panel-default">
            <!-- panel heading/header -->
            <div class="panel-heading">
              <h3 class="panel-title">General</h3>
            </div>
            <!--/ panel heading/header -->
            <%= form_for @forum do |f| %>
            	<!-- panel body -->
	            <div class="panel-body">
	              <form class="form-horizontal form-bordered" action="">
	                <div class="form-group">
	                  <label class="col-sm-3 control-label">Forum Name</label>
	                  <div class="col-sm-9">
                      <%= f.text_field :name, class: "form-control", type: "text" %>
                      <br/>
                      <%= f.submit "SUBMIT", class: "btn btn-primary btn-large pull-right p-t-20" %>
											<% end %>
	                  </div>
	                </div>
	              </form>
	            </div>
	            <!-- panel body -->
          </div>
          <!--/ END form panel -->
        </div>
      </div>
      <!--/ END row -->
       
    	<!-- START To Top Scroller -->
    	<a href="#" class="totop animation" data-toggle="waypoints totop" data-showanim="bounceIn" data-hideanim="	bounceOut" data-offset="50%"><i class="ico-angle-up"></i></a>
    	<!--/ END To Top Scroller -->

  	</section>
  	<!--/ END Template Main -->
  </body>
  <!--/ END Body -->
<%= render 'shared/js' %>
</html>

app/views/forums/show.html.erb
<!DOCTYPE html>
<!-- 
TEMPLATE NAME : Adminre backend
VERSION : 1.2.0
AUTHOR : JohnPozy
AUTHOR URL : http://themeforest.net/user/JohnPozy
EMAIL : pampersdry@gmail.com
LAST UPDATE: 23/06/2014

** A license must be purchased in order to legally use this template for your project **
** PLEASE SUPPORT ME. YOUR SUPPORT ENSURE THE CONTINUITY OF THIS PROJECT **
-->
<html class="backend">
  <%= render 'shared/backend_head' %>
  <%#= render 'shared/header' %>

  <!-- START Body -->
  <body>
    

     <%= render 'shared/header_member' %>


<!-- START Template Main -->
<section id="main" role="main">
  <!-- START Template Container -->
  <%#= render 'shared/navigation_member_secondary' %>
  <div class="container-fluid">
      <div class="container">

        <!-- panel heading -->
        <div class="panel-heading">
          <h3 class="semibold pull-left text-default">Forums / <small><%= @forum.name  %></small></h3>
            <!-- panel toolbar -->
            <div class="panel-toolbar">
                 <%= link_to "/topics/new?forum=#{@forum.id}" do %>
                   <button type="button" class="mt10 btn btn-primary pull-right" data-toggle="modal" data-target="#ModalComposeMessage">
                      <i class="ico-pencil5"></i> 
                      <span class="semibold">New Topic</span>
                  </button>
                  <% end %>
            </div>
        </div>
        <!--/ panel heading -->
      </div>

      <!-- START Table layout -->
      <div class="table-layout container pt30">
        <!-- message list-->
        <div class="col-lg-3 valign-top panel panel-minimal pr30 ">
          <!-- panel heading -->
          <div class="panel-heading">
            <!-- panel toolbar -->
            <div class="panel-toolbar">
                <h3 class="gf_muli">Recent Messages</h3>
            </div>
          </div>
          <!--/ panel heading -->

          <!-- panel body -->
          <div class="panel-body npl">
            <!-- message list -->
            <div class="media-list">
      			
        			<% @posts.take(6).each do |post| %>
        			
  	            <a href="<%= "/topics/#{post.topic_id}##{post.id}" %>" class="media">
	                <span class="pull-left">
	                  <img src="<%= post.user.avatar %>" class="media-object img-circle" alt="" width="50px" height="50px;">
	                </span>
	                <span class="media-body">
                    <span class="media-heading"><%= post.user.full_name_or_level %></span>
                    <span class="media-text ellipsis nm"><%= truncate post.content, length: 50%></span>
                    <!-- meta icon -->
                    <!-- <span class="media-meta"><i class="ico-star6"></i></span>
                    <span class="media-meta"><i class="ico-attachment"></i></span> -->
                    <span class="media-meta pull-left"><%= distance_of_time_in_words_to_now post.created_at %></span>
                    <!--/ meta icon -->
	                </span>
  	            </a>
        			<% end %>
        </div>
        <!-- message list -->
    </div>
    <!--/ panel body -->
              
          </div>
          <!--/ message list -->

          <!-- content -->
          <div class="col-lg-8 valign-top panel panel-default">
              <!-- panel toolbar wrapper -->
              <div class="panel-toolbar-wrapper pl0 pt5 pb5">
                  <!-- panel toolbar -->
                  <div class="panel-toolbar pl10">
                      <div class="btn-group">
						  <% unless Forum.count == 1%>
						  <% link_to forums_path do %>
	                          <button type="button" class="btn btn-default pull-left ws2">
	                            <i class="ico-arrow-left mr5"></i>
	                            Back to All Forums 
	                          </button>
							  <% end %>
						  <% end %>
                      </div>
                  </div>
                  <div class="panel-toolbar text-right">
            <% if @topics.any? %>
					  <%= link_to topic_path(@topics.first.id) do %>
                    <button type="button" class="btn btn-default pull-right">
                      <span class="bold mr5">Next: </span>
                      <span class="text-primary mr5"><%= @topics.first.name %></span>
                      <i class="ico-arrow-right ml5"></i>
                    </button>
					<% end %>
          <% end %>
                  </div>
                  <!--/ panel toolbar -->
              </div>
              <!--/ panel toolbar wrapper -->

              <!-- email list -->
              <div class="table-responsive">
                  <table class="table table-hover table-email" id="table-email">
                      <thead>
                       <!--  <th width="1%"></th>
                        <th width="1%"></th> -->
                        <th width="50%">Topic or Question</th>
                        <th width="5%">Posts</th>
                        <th width="5%">Views</th>
                        <th width="20%">Activity</th>
                      </thead>
                      <tbody>
                        <% @topics.each do |topic| %>
                          <tr>
                           <!--  <td width="2%">
                            <div class="checkbox custom-checkbox nm">  
                                <input type="checkbox" id="customcheckbox1" value="1" data-toggle="selectrow" data-target="tr">  
                                <label for="customcheckbox1"></label>   
                            </div>
                            </td>
                            <td width="2%">
                              <span class="checkbox checkbox-icon icon-star">  
                                <input type="checkbox" id="checkboxicon1" value="1">  
                                <label for="checkboxicon1"></label>   
                              </span>
                            </td> -->
                            <td class="meta">
                                <h5 class="semibold mb0">
                                  <%= link_to h(topic.name), topic_path(topic.id) %>
                                </h5>
                                <p class="date small mt5"><em>Created <%= date_with_slashes(topic.created_at) %></em></p>
                            </td>
                            <td class="text-center semibold"><%= [topic.posts.count - 1,0].max %></td>
                            <td class="text-center semibold"><%= topic.visit.total_visits %></td>
                            <td>
                             <small>
                              <span class="semibold">
                                <%= link_to topic.user.full_name_or_level, "/users/#{topic.last_poster_id}" %>
                              </span>
                                <br/>
                              <span class="text-muted regular mt0">
                                <em><%= distance_of_time_in_words_to_now topic.last_post_at %> ago <!-- by --> 
									<%#= link_to user_path(User.find(topic.last_poster_id)) do %>
									<%#= topic.user.full_name_or_level  %>
									<%# end %>
                                </em> 
                              </span>
                              
                             </small>
                            </td>
                        </tr>
                        <% end %>
                      </tbody>
                  </table>
              </div>
              <!--/ email list -->
          </div>
          <!--/ content -->
        </div>
        <!--/ END Table layout -->
    </div>
    <!--/ END Template Container -->

    <!-- START To Top Scroller -->
    <a href="#" class="totop animation" data-toggle="waypoints totop" data-showanim="bounceIn" data-hideanim="bounceOut" data-offset="50%"><i class="ico-angle-up"></i></a>
    <!--/ END To Top Scroller -->

</section>

<!--/ END Template Main -->
  </body>
  <!--/ END Body -->
<%= render 'shared/js' %>
</html>
<!--/ END Template Main -->

<%#= link_to "New Forum", new_forum_path %>
<%#= link_to "Show", forum %>
<%#= link_to "Edit", edit_forum_path(forum) %>
<%#= link_to "Destroy", forum, :confirm => 'Are you sure?', :method => :delete %>

<%#= link_to "Show", topic %>
<%#= link_to "Edit", edit_topic_path(topic) %>
<%#= link_to "Destroy", topic, :confirm => 'Are you sure?', :method => :delete %>