config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  
  resources :users do
  end
  
  resources :forums
  resources :topics
  resources :posts
  
  resources :sessions
  get "login" => "sessions#new", as: :login
  get "signup" => "users#new", as: :signup
  get "home" => "users#index", as: :home
  
  get "lawyers" => "users#lawyers", as: :lawyers
  
  resources :password_resets, only: %w(new create edit update)
  
  get '/404', to: 'errors#not_found'
  get '/422' => 'errors#server_error'
  get '/500' => 'errors#server_error'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :forum
  has_many :posts, :dependent => :destroy
  belongs_to :user
  has_one :visit, :as => :visitable
  
  # forum
  has_many :posts
  accepts_nested_attributes_for :posts, :reject_if => :all_blank, :allow_destroy => true
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @topic = Topic.new
    @post = @topic.posts.build
    @user = current_user
    @posts = Post.all.each.sort {|a,b| b.created_at <=> a.created_at}
  end
  
  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      @topic.update_attributes(:last_poster_id => current_user.id, :last_post_at => Time.now)
      
     redirect_to forum_path(@topic.forum_id)
    else
      render :action => 'new'
    end
  end
  
  def show
    @topic = Topic.find(params[:id])
    @forum = Forum.find(@topic.forum_id)
    @user = current_user
    @first_post = @topic.posts.first
    @posts = Post.all.each.sort {|a,b| b.created_at <=> a.created_at}
    @controller = params[:controller]
    @action = params[:action]
    Visit.track(@topic, @controller, @action , request.remote_ip)
  end
  
  def edit
    
  end
  
  protected
  
  def topic_params
    params.require(:topic).permit(:name, :forum_id, :user_id, :last_poster_id, :last_post_at, posts_attributes: [:id, :topic_id, :user_id, :content, :_destroy] )
  end
  
  def find_forum
    @group = Group.find_by_slug!(params[:group_id]) 
    @forum = @group.forum
  end
  
end

app/views/topics/new.html.erb
<!DOCTYPE html>
<!-- 
TEMPLATE NAME : Adminre backend
VERSION : 1.2.0
AUTHOR : JohnPozy
AUTHOR URL : http://themeforest.net/user/JohnPozy
EMAIL : pampersdry@gmail.com
LAST UPDATE: 23/06/2014

** A license must be purchased in order to legally use this template for your project **
** PLEASE SUPPORT ME. YOUR SUPPORT ENSURE THE CONTINUITY OF THIS PROJECT **
-->
<html class="backend">
    <%= render 'shared/backend_head' %>
    <%#= render 'shared/header' %>

    <!-- START Body -->
    <body>
    

     <%= render 'shared/header_member' %>

     <!-- START Template Main -->
      <section id="main" role="main">
      	<%#= render 'shared/navigation_member_secondary' %>


        <!-- START Template Container -->
      	<div class="container-fluid">
			    <div class="container">
			      <!-- panel heading -->
			      <div class="panel-heading">
			        <h3 class="semibold pull-left text-default">New Forum Topic or Question</h3>
			        <!-- panel toolbar -->
			        <div class="panel-toolbar">
			         
			        </div>
			      </div>
			      <!--/ panel heading -->
			    </div>

			    <!-- START row -->
	        <div class="row">
						<!-- START Table layout -->
				   	<div class="table-layout container pt30">
		        	
		        	<!-- message list-->
				     	<div class="col-lg-3 valign-top panel panel-minimal pr30 npl">
				        <!-- panel heading -->
				        <div class="panel-heading">
                  <!-- panel toolbar -->
                  <div class="panel-toolbar">
                      <h3>Recent Messages</h3>
                  </div>
                </div>
                <!--/ panel heading -->

					    	<hr class="mt10 mb10"><!-- horizontal line -->
					    
						    <!-- panel body -->
						    <div class="panel-body">
						        <!-- message list -->
						        <div class="media-list">
									
									
									<% @posts.take(6).each do |post| %>
						                <a href="<%= "/topics/#{post.topic_id}##{post.id}" %>" class="media">
						                <span class="pull-left">
						                    <img src="<%= post.user.avatar %>" class="media-object img-circle" alt="" width="50px" height="50px;">
						                </span>
						                <span class="media-body">
						                    <span class="media-heading"><%= post.user.full_name_or_level %></span>
						                    <span class="media-text ellipsis nm"><%= truncate post.content, length: 50%></span>
						                    <!-- meta icon -->
						                    <span class="media-meta"><i class="ico-star6"></i></span>
						                    <span class="media-meta"><i class="ico-attachment"></i></span>
						                    <span class="media-meta pull-right"><%= distance_of_time_in_words_to_now post.created_at %></span>
						                    <!--/ meta icon -->
						                </span>
										</a>
						           	
									      
									<% end %>
									
									
						        </div>
						        <!-- message list -->
						    </div>
						    <!--/ panel body -->
				      </div>
				      <!--/ message list -->

				      <!-- content -->
				      <div class="col-lg-8">
	              <!-- START panel -->
	              <div class="panel panel-default">
                  <!-- panel heading/header -->
                  <div class="panel-heading">
                      <h3 class="panel-title">General</h3>
                  </div>
                  <!--/ panel heading/header -->
                  <!-- panel body -->
                  <div class="panel-body">
                    <div class="form-horizontal form-bordered" action="">
		                  <h4 class="text-primary mt0">New Forum topic or Question</h4>
		                  <p class="pb10">Individual form controls automatically receive some global styling. All textual for optimum spacing.</p>

											<!-- NEW FORUM FORM -->
	              			<%= form_for @topic do |f| %>

		              			<% if params[:forum] %>
		              				<%= f.hidden_field :forum_id, value: params[:forum] %>
				                    <div class="form-group">
			                        <label class="col-sm-3 control-label">Quick Description</label>
			                        <div class="col-sm-9">
			                            <%= f.text_field :name, :class => 'form-control' %>
			                            <%= f.hidden_field :user_id, value: current_user.id %>
			                        </div>
				                    </div>

				                    <%= f.fields_for :posts do |post| %>
				                     	<div class="form-group">
			                        	<label class="col-sm-3 control-label">More Info</label>
			                        	<div class="col-sm-9">
				                    			<%= post.text_area :content, :size => "80x20", :class => 'form-control', rows: '10', placeholder: "Use this field to provide additional information..." %>
				                    			<%= post.hidden_field :user_id, value: current_user.id %>
				                        </div>
				                      </div>
				                    <% end %>

				                    <div class="panel-footer">
				                      <div class="form-group no-border">
				                        <div class="col-sm-6 col-sm-offset-3">
				                        	<%= f.submit "Post Topic or Question", :class => 'btn btn-primary btn-lg btn-block pull-right ws2' %>
				                        </div>
				                      </div> 
				                    </div>
		            				<% end %>
		            			<% end %>
            				<!-- NEW FORUM FORM -->
						</div>
              		</div>    
                </div>
                <!--/ END row -->
              </div>
            </div>
            <!--/ END Template Container -->
          </div>
        </div>

      	<!-- START To Top Scroller -->
      	<a href="#" class="totop animation" data-toggle="waypoints totop" data-showanim="bounceIn" data-hideanim="	bounceOut" data-offset="50%"><i class="ico-angle-up"></i></a>
      	<!--/ END To Top Scroller -->

    	</section>
    	<!--/ END Template Main -->

        
    </body>
    <!--/ END Body -->

<%= render 'shared/js' %>
</html>

app/views/topics/show.html.erb
<!DOCTYPE html>
<!-- 
TEMPLATE NAME : Adminre backend
VERSION : 1.2.0
AUTHOR : JohnPozy
AUTHOR URL : http://themeforest.net/user/JohnPozy
EMAIL : pampersdry@gmail.com
LAST UPDATE: 23/06/2014

** A license must be purchased in order to legally use this template for your project **
** PLEASE SUPPORT ME. YOUR SUPPORT ENSURE THE CONTINUITY OF THIS PROJECT **
-->
<html class="backend">
  <%= render 'shared/backend_head' %>
  <%#= render 'shared/header' %>

  <!-- START Body -->
  <body>
  

   <%= render 'shared/header_member' %>

   <!-- START Template Main -->
    <section id="main" role="main">
      <%#= render 'shared/navigation_member_secondary' %><!-- START Template Container -->
    	<div class="container">
        <button type="button" class="btn btn-success pull-right" data-toggle="modal" data-target="#ModalComposeMessage"><i class="ico-pencil5"></i> Compose Message</button>
      </div>
      <!-- Page Header -->

      <div class="container-fluid">
        <div class="container">
          <!-- START Table layout -->
          <div class="table-layout">
            <!-- message list-->
            <div class="col-lg-3 valign-top panel panel-minimal npl">
                <!-- panel heading -->
                <div class="panel-heading">
                  <!-- panel toolbar -->
                  <div class="panel-toolbar">
                      <h4 class="gf_muli">Recent Messages</h4>
                  </div>
                </div>
                <!--/ panel heading -->


                <!-- panel body -->
                <div class="panel-body npl">
                  <!-- message list -->
                  <div class="media-list">
    					      <% @posts.take(6).each do |post| %>
                      <a href="<%= "/topics/#{post.topic_id}##{post.id}" %>"  class="media">
                        <span class="pull-left">
                            <img src="<%= post.user.avatar %>" class="media-object img-circle" alt="" width="50px" height="50px;">
                        </span>
                        <span class="media-body">
                            <span class="media-heading"><%= post.user.full_name_or_level %></span>
                            <span class="media-text ellipsis nm"><%= truncate post.content, length: 50%></span>
                            <!-- meta icon -->
                            
                            <span class="media-meta pull-right"><%= distance_of_time_in_words_to_now post.created_at %></span>
                            <!--/ meta icon -->
                        </span>
                      </a>
    					      <% end %>
                  </div>
                    <!-- message list -->
                </div>
                <!--/ panel body -->
              </div>
              <!--/ message list -->

            <!-- content -->
            <div class="col-md-8">
              <div class="valign-top panel panel-default">
                <!-- toolbar -->
                <div class="panel-toolbar-wrapper pt10 pb10">
                    <div class="panel-toolbar">
                        <div class="btn-group">
                        <%= link_to forum_path(@topic.forum_id) do %>
                      	 <button type="button" class="btn btn-default pull-left ws2">
                            <i class="ico-arrow-left mr5"></i>
                          Back to All Topics 
                        </button>
                      <% end %>
                    </div>
                </div>
                <div class="panel-toolbar text-right">
                  <%= link_to topic_path(@forum.next_topic(@topic.id)) do %>
                    <button type="button" class="btn btn-default pull-right">
                      <span class="bold mr5">Next: </span>
                      <span class="text-primary"><%= @forum.next_topic(@topic.id).name %></span>
                      <i class="ico-arrow-right ml5"></i>
                  </button>
                  <% end %>
                </div>
              </div>
              <!--/ toolbar -->

    		      <% @topic.name %>
    							 
							<!-- panel body -->
              <div class="panel-body"  style="padding: 25px 50px;">
                  <!-- sender detail -->
                  <ul class="list-table">
                      <li style="width:100px;">
                          <img class="img-circle" src="<%= @topic.user.avatar %>" alt="" width="95px" height="95px">
                      </li>
                      <li class="text-left">
                          <h4 class="semibold ellipsis">
                              <%= link_to @first_post.user.full_name, user_url(@first_post.user) %><br/>
                              <small class="text-muted mt0">
                                <a href="javascript:void(0);"><%= %></a>
                              </small>
                              <br/>
                              <h5><small class="fs12 text-muted"><em><%= @topic.created_at.strftime("%b %-d, %Y")%></em></small></h5>
                          </h4>
                      </li>
                      <!-- <li class="text-right">
                          <button class="btn btn-default">Private Message</button>
                          <%#= link_to "#{new_post_path}?topic=#{@topic.id}" do %>
                            <button class="btn btn-primary">Follow</button>
                          <%# end%>
                          <button class="btn btn-info">Like</button>
                      </li> -->
                  </ul>
                  <!--/ sender detail -->
              </div>
              <!--/ panel body -->

              <!-- panel body -->
              <div class="panel-body slimscroll" style="padding: 20px 50px; background: #f3f3f3; margin: 0 50px 50px 0; border-radius: 0 6px 6px 0; border: 1px solid #e5e5e5; border-left: none;">
                  <h3 class="semibold mt0 mb10">Forum post topic or question</h3>
                  <p><%= @first_post.content %></p>
              </div>
              <!--/ panel body -->

              <hr class="nm"><!-- horizontal line -->

              <!-- panel body -->
                <div class="panel-body bgcolor-default" style="padding-left: 50px;">
                    <h4 class="semibold text-primary pull-left"> Comments (<%= @topic.posts.count - 1 %>)</h4>
                    
                    <a href="#reply" class="btn btn-default pull-right mr30">Reply</a>
                </div>
                <!--/ panel body -->

              <hr class="nm"><!-- horizontal line -->

              <!-- Comments -->
              <section class="panel-body pt30" style="padding: 0 50px 50px 75px;">
                <div class="media-list media-list-bubble">
                    <% @topic.posts.offset(1).each do |post| %>
                     <a id="<%= post.id %>"></a>
                      <div class="media">
                          <a href="javascript:void(0);" class="media-object pull-left">
                              <img src="<%= post.user.avatar %>" class="img-circle" alt="">
                          </a>
                          <div class="media-body">
                              <div class="media-text">
                                  <h5 class="semibold mt0 mb5 text-default"><%= link_to post.user.full_name, user_url(post.user) %></h5>
                                  <p class="mb5"><%= post.content %></p>
                                  <!-- meta icon -->
                                  <p class="mb0">
                                      <span class="media-meta"><%= post.created_at.strftime("%b %-d, %Y")%></span><!-- 
                                      <span class="mr5 ml5 text-muted">&#8226;</span>
                                      <a href="javascript:void(0);" class="media-meta text-default" data-toggle="tooltip" title="Like"><i class="ico-heart"></i></a>
                                  </p> -->
                                  <!--/ meta icon -->
                              </div>
                          </div>
                      </div>
                    <% end %>
                </div>
              </section>
              <!-- Comments -->

                <!-- Post Comments -->
                <section id="reply" class="panel-footer pb0" style="padding: 25px 50px;">
                  <h4 class="mt0 mb15 bold">Post your comment</h4>
                  <!-- form -->
                  <div class="form-horizontal" data-toggle="formajax" data-options='{ "url": "server/form-ajax.php" }'>
                    <div class="form-group message-container">
                      <div class="alert alert-danger">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h4 class="mt0 mb5 semibold">No Spamming</h4>
                        <p class="nm">Please do not spam. Any spamming activity will not be tolerated.</p>
                      </div>
                    </div><!-- will be use as done/fail message container -->

                    <hr/>

                    <div class="form-group">
                      <div class="col-sm-2">
                        <img src="<%= current_user.avatar %>" class="img-circle img-responsive" alt="">
                      </div>
                      <div class="col-sm-10">
                        <h4 class="semibold text-primary">
                            <%= current_user.full_name %>
                        </h4>
        								<%= form_for Post.new do |f| %>
        								<%= f.text_area :content, placeholder: "Enter comment here...", rows: 10, class: "form-control" %>
        								<%= f.hidden_field :user_id, value: current_user.id %>
        								<%= f.hidden_field :topic_id, value: @topic.id %>
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="col-sm-12">
					              <%= f.submit "Submit", class: "btn btn-success ladda-button" %>
                      </div>
					           <% end %>
                    </div>
			            </div>
                  <!-- form -->
                </section>
                    <!--/ Post Comments -->
              </div>
                <!--/ content -->
            </div>
            <!--/ END Table layout -->
          </div>
        </div>
        <!--/ END Template Container -->
      </div>
    </section>

  </body>

</html>



  <%#= link_to "Edit", edit_post_path(post) %>
  <%#= link_to "Delete", post, :confirm => 'Are you sure?', :method => :delete %>
  <%#= link_to "Destroy Topic", @topic, :confirm => 'Are you sure?', :method => :delete %>
 