config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  
  resources :users do
  end
  
  resources :forums
  resources :topics
  resources :posts
  
  resources :sessions
  get "login" => "sessions#new", as: :login
  get "signup" => "users#new", as: :signup
  get "home" => "users#index", as: :home
  
  get "lawyers" => "users#lawyers", as: :lawyers
  
  resources :password_resets, only: %w(new create edit update)
  
  get '/404', to: 'errors#not_found'
  get '/422' => 'errors#server_error'
  get '/500' => 'errors#server_error'

end

app/views/shared/_backend_head.html.erb
<!DOCTYPE html>
<!-- 
TEMPLATE NAME : Adminre backend
VERSION : 1.2.0
AUTHOR : JohnPozy
AUTHOR URL : http://themeforest.net/user/JohnPozy
EMAIL : pampersdry@gmail.com
LAST UPDATE: 23/06/2014

** A license must be purchased in order to legally use this template for your project **
** PLEASE SUPPORT ME. YOUR SUPPORT ENSURE THE CONTINUITY OF THIS PROJECT **
-->
<html class="backend">
    <!-- START Head -->
    <head>
        <!-- START META SECTION -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>BlackCFA</title>
        <meta name="author" content="pampersdry.info">
        <meta name="description" content="Adminre is a clean and flat backend and frontend theme build with twitter bootstrap 3.1.1">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../image/touch/apple-touch-icon-144x144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../image/touch/apple-touch-icon-114x114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../image/touch/apple-touch-icon-72x72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="../image/touch/apple-touch-icon-57x57-precomposed.png">
        <link rel="shortcut icon" href="../image/favicon.ico">
        <!--/ END META SECTION -->

        <!-- START STYLESHEETS -->
        <!-- Plugins stylesheet : optional -->
        
        
        <!--/ Plugins stylesheet -->

        <!-- Application stylesheet : mandatory -->
        <link rel="stylesheet" href="/library/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="/stylesheet/layout.min.css">
        <link rel="stylesheet" href="/stylesheet/uielement.min.css">
        <link rel="stylesheet" href="/stylesheet/custom.css">
        <!--/ Application stylesheet -->
        <!-- END STYLESHEETS -->


    </head>
    <!--/ END Head -->

app/views/shared/_dropdown-menu_member.html.erb
<!-- START Right nav -->
<ul class="nav navbar-nav navbar-right">
    <!-- Profile dropdown -->
    <li class="dropdown profile">
        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
            <span class="meta">
                <span class="avatar"><img src="<%= @user.avatar %>" class="img-circle" alt="" /></span>
                <span class="text hidden-xs hidden-sm pl5"><%= @user.full_name %></span>
                <span class="caret"></span>
            </span>
        </a>
        <ul class="dropdown-menu" role="menu">
         
           <li class="divider"></li>
            <li><a href="<%= users_path(@user) %>"><span class="icon"><i class="ico-user-plus2"></i></span> BlackCFA</a></li>
            <li><a href="<%= user_path(@user) %>"><span class="icon"><i class="ico-user"></i></span> My Profile</a></li>
            <li><a href="<%= edit_user_path(@user) %>"><span class="icon"><i class="ico-cog4"></i></span> Edit Profile</a></li>
            <li class="divider"></li>
            <li>
                <%= link_to session_path(current_user.id), method: :delete do %>
                <span class="icon"><i class="ico-exit"></i></span> Log Out
                <% end %>
            </li>
            
        </ul>
    </li>
    <!-- Profile dropdown -->
</ul>
<!--/ END Right nav -->

app/views/shared/_frontend_footer.html.erb
<!-- START Template Footer -->
<footer id="footer" role="contentinfo" class="pt60 pb60">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <!-- About -->
            <div class="col-md-7">
                <h5 class="mt0">About Us</h5>
                <p>BlackCFA was founded in July 2014. The orgnaization is dedicated dedicated to connecting, supporting, and empowering black professionals that have achieved the CFA designation and those pursuing the CFA course of study. Stay tuned, we've got big plans.</p>
            </div>
            <!--/ About -->

            <!-- Address + Social -->
            <div class="col-md-3">
                <h5 class="mt0">Contact Us</h5>
                <address>
                    <strong>Black CFA</strong><br>
                    Washington, DC 94107<br>
                </address>
            </div>
            <!--/ Address + Social -->

             <!-- Address + Social -->
            <div class="col-md-2">
                <h5 class="font-alt mt0">Stay Connected</h5>
                <a href="javascript:void(0);" class="text-muted mr15" data-toggle="tooltip" title="Facebook"><i class="ico-facebook2"></i></a>
                <a href="javascript:void(0);" class="text-muted mr15" data-toggle="tooltip" title="Twitter"><i class="ico-twitter2"></i></a>
                <a href="javascript:void(0);" class="text-muted mr15" data-toggle="tooltip" title="Google+"><i class="ico-google-plus2"></i></a>
            </div>
            <!--/ Address + Social -->
        </div>
        <!--/ row -->
    </div>
    <!--/ container -->

   <!-- bottom footer -->
    <div class="footer-bottom mt60">
        <!-- container -->
        <div class="container">
            <div class="row">
                <div class="col-sm-6 copyright">
                    <!-- copyright -->
                    <p class="nm copyright">&copy; Copyright 2014 by <a href="javascript:void(0);" class="">The Wildfyre Group</a>. All Rights Reserved.</p>
                    <!--/ copyright -->
                </div>
                <div class="col-sm-6 text-right legal">
                    <a href="javascript:void(0);" class="">Privacy Policy</a>
                    <span class="ml5 mr5">&#8226;</span>
                    <a href="javascript:void(0);" class="">Terms of Service</a>
                </div>
            </div>
        </div>
        <!--/ container -->
    </div>
    <!--/ bottom footer -->
</footer>
<!--/ END Template Footer -->

app/views/shared/_frontend_head.html.erb
<!DOCTYPE html>
<!-- 
TEMPLATE NAME : Adminre frontend
VERSION : 1.2.0
AUTHOR : JohnPozy<!DOCTYPE html>

TEMPLATE NAME : Adminre frontend
VERSION : 1.2.0
AUTHOR : JohnPozy
AUTHOR URL : http://themeforest.net/user/JohnPozy
EMAIL : pampersdry@gmail.com
LAST UPDATE: 23/06/2014

** A license must be purchased in order to legally use this template for your project **
** PLEASE SUPPORT ME. YOUR SUPPORT ENSURE THE CONTINUITY OF THIS PROJECT **
-->
<html class="frontend">
    <!-- START Head -->
    <head>
        <!-- START META SECTION -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>BlackCFA</title>
        <meta name="author" content="pampersdry.info">
        <meta name="description" content="Adminre is a clean and flat backend and frontend theme build with twitter bootstrap 3.1.1">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../image/touch/apple-touch-icon-144x144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../image/touch/apple-touch-icon-114x114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../image/touch/apple-touch-icon-72x72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="../image/touch/apple-touch-icon-57x57-precomposed.png">
        <link rel="shortcut icon" href="../image/favicon.ico">
        <!--/ END META SECTION -->

        <!-- START STYLESHEETS -->
        <!-- Plugins stylesheet : optional -->
        <link rel="stylesheet" href="/plugins/owl/css/owl.carousel.min.css">
        
        <link rel="stylesheet" href="/plugins/layerslider/css/layerslider.min.css">
        
        <!--/ Plugins stylesheet -->

        <!-- Application stylesheet : mandatory -->
        <link rel="stylesheet" href="/library/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="/stylesheet/layout.css">
        <link rel="stylesheet" href="/stylesheet/uielement.css">
        <link rel="stylesheet" href="/stylesheet/custom.css">
        <!--/ Application stylesheet -->
        <!-- END STYLESHEETS -->
        
    </head>
    <!--/ END Head -->

app/views/shared/_header_member.html.erb
<!-- START Template Header -->
<header id="header" class="navbar navbar-fixed-top">
    <div class="container">
        <!-- START navbar header -->
        <div class="navbar-header">
            <!-- Brand -->
            <a class="navbar-brand" href="/">
                <span class="logo-figure" style="margin-left:-4px;"></span>
                <span class="logo-text"></span>
            </a>
            <!--/ Brand -->
        </div>
        <!--/ END navbar header -->

        <!-- START Toolbar -->
        <div class="navbar-toolbar clearfix">
            <!-- START Left nav -->
            <%= render 'shared/navigation_member' %>
            <!--/ END nav collapse -->
        </div>
        <!--/ END Toolbar -->
    </div>
</header>
<!--/ END Template Header --> 

app/views/shared/_header_visitor.html.erb
<!-- START Template Header -->
<header id="header" class="navbar navbar-fixed-top">
    <div class="container">
        <!-- START navbar header -->
        <div class="navbar-header">
            <!-- Brand -->
            <a class="navbar-brand" href="/">
                <span class="logo-figure" style="margin-left:-4px;"></span>
                <span class="logo-text"></span>
            </a>
            <!--/ Brand -->
        </div>
        <!--/ END navbar header -->

        <!-- START Toolbar -->
        <div class="navbar-toolbar clearfix">
            <!-- START Left nav -->
            <%= render 'shared/navigation_visitor' %>
            <!--/ END nav collapse -->
        </div>
        <!--/ END Toolbar -->
    </div>
</header>
<!--/ END Template Header --> 

app/views/shared/_js.html.erb
<!-- START JAVASCRIPT SECTION (Load javascripts at bottom to reduce load time) -->
<!-- Library script : mandatory -->
<script type="text/javascript" src="/library/jquery/js/jquery.min.js"></script>
<script type="text/javascript" src="/library/jquery/js/jquery-migrate.min.js"></script>
<script type="text/javascript" src="/library/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/library/core/js/core.min.js"></script>
<!--/ Library script -->

<!-- App and page level script -->
<script type="text/javascript" src="/plugins/sparkline/js/jquery.sparkline.min.js"></script><!-- will be use globaly as a summary on sidebar menu -->
<script type="text/javascript" src="/javascript/app.min.js"></script>


<script type="text/javascript" src="/plugins/magnific/js/jquery.magnific-popup.min.js"></script>

<script type="text/javascript" src="/javascript/pages/timeline.js"></script>

<!--/ App and page level script -->
<!--/ END JAVASCRIPT SECTION -->

app/views/shared/_navigation_member.html.erb
<div class="collapse navbar-collapse navbar-collapse-alt" id="navbar-collapse">
    <ul class="nav navbar-nav navbar-right">
        <!-- <li class="dropdown">
            <a href="#">
                <span class="meta">
                    <span class="text">
                         <span class="ico-building"></span>
                         Companies
                     </span>
                </span>
            </a>
        </li> -->
        <li class="dropdown">
            <a href="<%= lawyers_path %>">
                <span class="meta">
                    <span class="text">
                        <span class="ico-certificate2"></span>
                        Charterholders
                    </span>
                </span>
            </a>
        </li>
        <li class="dropdown">
            <a href="<%= users_path %>">
                <span class="meta">
                    <span class="text">
                        <span class="ico-users"></span>
                        Member Directory
                    </span>
                </span>
            </a>
        </li>
		<% if Forum.count == 1 %>
        <li class="dropdown">
            <a href="/forums/<%= "#{Forum.last.id}"%>">
                <span class="meta">
                    <span class="text">
                        <span class="ico-bubble3"></span>
                        Forum
                    </span>
                </span>
            </a>
        </li>
		
		<% else %>
		
        <li class="dropdown">
            <a href="/forums">
                <span class="meta">
                    <span class="text">
                        <span class="ico-bubble3"></span>
                        Forums
                    </span>
                </span>
            </a>
        </li>
		
		<% end %>
		
        <li class="dropdown">
             <a href="#">
            </a>
        </li>
        <!-- Profile dropdown -->
        <li class="dropdown profile bgcolor-black">
            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                <span class="meta">
                    <span class="avatar">
                        <img src="<%= @user.avatar %>" class="img-circle" height="30" alt="" />
                    </span>
                    <span class="text hidden-xs hidden-sm ml10"><%= @user.first_name %></span>
                    <span class="caret"></span>
                </span>
            </a>
            <ul class="dropdown-menu" role="menu">
                <li class="pa15">
                    <h5 class="semibold hidden-xs hidden-sm">
                        <p class="nm">Follow Us!</p>
                        <small class="text-muted">Stay connected @blackcfa.</small>
                    </h5>
                    <br>
                    <!-- Go to www.addthis.com/dashboard to customize your tools -->
                    <div class="addthis_native_toolbox"></div>
                </li>
                <li class="divider"></li>
                <li><a href="<%= users_path %>"><span class="icon"><i class="ico-user-plus2"></i></span> BlackCFA Directory</a></li>
                <li><a href="<%= user_path(@user) %>"><span class="icon"><i class="ico-user"></i></span> My Profile</a></li>
                <li><a href="<%= edit_user_path(@user) %>"><span class="icon"><i class="ico-cog4"></i></span> Edit Profile</a></li>
                <li class="divider"></li>
                <li>
                    <%= link_to session_path(current_user.id), method: :delete do %>
                        <span class="icon"><i class="ico-exit"></i></span> Log Out
                    <% end %>
                </li>
                
            </ul>
        </li>
        <!-- Profile dropdown -->
    </ul>

app/views/shared/_navigation_visitor.html.erb
<div class="collapse navbar-collapse navbar-collapse-alt" id="navbar-collapse">
    <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
            <a href="#">
                <span class="meta">
                    <span class="text">About Us</span>
                </span>
            </a>
        </li>
        <li class="dropdown">
            <a href="#">
                <span class="meta">
                    <span class="text">Charterholdering Members</span>
                </span>
            </a>
        </li>
        <li class="dropdown">
            <a href="#">
                <span class="meta">
                    <span class="text">Our Partners</span>
                </span>
            </a>
        </li>
        <li class="dropdown">
            <a href="#">
            </a>
        </li>
        <li class="dropdown nh">
            <a href="<%= login_path %>" class="npl">
                <span class="btn btn-transparent">
                    <span class="">LOGIN</span>
                </span>
            </a>
        </li>
        <li class="dropdown nh">
            <a href="<%= signup_path %>" class="np">
                <span class="btn btn-transparent">
                    <span class="bold">SIGN UP </span>
                </span>
            </a>
        </li>
    </ul>
</div>